import type { Metadata } from "next";
import { Audiowide, Doto, Geist_Mono, JetBrains_Mono, Lexend, Orbitron } from "next/font/google";
import "./globals.css";

const geistSans = Lexend({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = JetBrains_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const digital = Orbitron({
//   variable: "--font-digital",
//   weight: "400",
// })
export const digital = Orbitron({
  variable: "--font-digital",
  weight: "700",
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${digital.variable} antialiased ${geistSans.className}`}
      >
        {children}
      </body>
    </html>
  );
}
